### ISSUE TITLE
Question regarding OP_MUL and if I did all this right =)

### ISSUE THREAD

**Issue by GenTarkin** [markblundeberg/coinsplitter_checkdatasig#11]
I just want to make sure I did this right.
Using the hardware/offline wallet method I did the following:
For CDS - ensured electron was on CDS network then followed all steps using CDS split method for the 1000 satoshi tx from offline / hardware wallet -> electron contract address -> output back to offline/ hardware wallet address -> created new tx on offline / hardware that spent entire wallets balance including the tiny contract address to a different address in wallet.
Everything confirmed, have over 100 confirmations on the above.

After the above, I then did the same thing with electron pointed at the non CDS network then used the split MUL tool on that network ... everything confirmed.

So, I should have non replayable coins on each chain now correct?

**Comment by markblundeberg** [comment]
Hi @GenTarkin sorry about the delay, I hope you got it all figured out!

**Comment by markblundeberg** [comment]
Yeah, I think that should have been quite effective. I did something very similar to that on Fork day.
