### ISSUE TITLE
Bitcoin Cash SV

### ISSUE THREAD

**Issue by gelsonspessatto** [markblundeberg/coinsplitter_checkdatasig#13]
Hi!

I followed the steps in this tutorial to claim my Bitcoin Cash SV: https://support.ledgerwallet.com/hc/en-us/articles/360012270054?input_string=bitcoin+cash+sv

I didnt finish the step 7 because i didnt want to spend my BSV. But now I don't know if that step is obligatory to successfully claim my BSV.

I am sending a print from my screen to help me explain. So my question is: this amount that I have in my wallet is BSV already? Or should I follow some additional step to conclude my claim?

Thanks for your help, bye!

![bsv](https://user-images.githubusercontent.com/45609555/49475209-c6450a00-f7fd-11e8-8a17-b14aa67da193.jpg)

**Comment by markblundeberg** [comment]
Hi, if you followed that guide up to step 7 but didn't do step 7, it should be fine. At this point you have used your coins in a transaction on BCH chain that cannot be replayed onto BSV chain.

**Comment by gelsonspessatto** [comment]
So what I possess can already be considered BCHSV??

**Comment by markblundeberg** [comment]
Yes, one unfortunate thing is that electron cash just says "BCH" whether it's BCH-ABC or BCH-BSV. You can only really know which one you are transacting by selecting the right servers.
