### ISSUE TITLE
OP_MUL Splitting option in 3.3.2CS

### ISSUE THREAD

**Issue by skywills** [markblundeberg/coinsplitter_checkdatasig#5]
i m performing two-way split and i had done the OP_CHECKDATASIGVERIFY split, but i din saw any option for OP_MUL Splitting.

 1.) may i know how to use the OP_MUL Splitting?
 2.) how to double check both split is successful and my coin are replay protected on both side

**Comment by markblundeberg** [comment]
Hi, I just posted a guide on reddit here, where Step 4 describes the splitting verification process

https://www.reddit.com/r/btc/comments/9yefov/if_you_want_to_dump_bsv_some_tips_on_splitting/

**Comment by markblundeberg** [comment]
In 3.3.2CS you should definitely see an option for MUL splitting. Is it not there?

![screenshot from 2018-11-19 02-08-24](https://user-images.githubusercontent.com/36528214/48700107-053d5380-eba0-11e8-8ce7-8ea208903ab5.png)

**Comment by skywills** [comment]
My fault, i am following the electroncash.org link to download 3.3.1CS instead of 3.3.2CS.

and thanks for sharing the link.
