### ISSUE TITLE
Error when trying to create split contract. MacOS High Sierra - Ledger Nano

### ISSUE THREAD

**Issue by B45h** [markblundeberg/coinsplitter_checkdatasig#9]
Following the instructions from the Ledger site
https://support.ledgerwallet.com/hc/en-us/articles/360012270054-Safely-claim-Bitcoin-Cash-SV

I get stuck on step 4, see attached image for error message once I hit "broadcast"

<img width="968" alt="screen shot 2018-11-24 at 19 31 33" src="https://user-images.githubusercontent.com/45330488/48978441-56b77800-f0a3-11e8-9a92-cb474b5aa24f.png">

Any ideas where I'm going wrong or what the problem is?

**Comment by markblundeberg** [comment]
Hi @B45h, hope you figured it out in the end. I missed the notification for this issue.

It looks like you were not connected to a BCH server, but rather a BSV one.

**Comment by B45h** [comment]
Thanks,

I didn't sort it out. I've just looked at the servers but can't really make sense of it. 
Would I need to start the process again once I've changed servers?

**Comment by markblundeberg** [comment]
The 'split coin' you made should still be there, and if you open up the dialog again then it should find it.
